### ISSUE TITLE
This is kinda useless

### ISSUE THREAD

**Issue by AlanB1978** [xxRockOnxx/vue2-timepicker#28]
There's no events being triggered. Checked the source and doesn't seem to have events either.

**Comment by lemuelflores** [comment]
What events would you want? Add your use case as well. If you just wanted to see if the value changed, you can just watch the variable. If you wanted to know if it opened, just listen for the click? and there is a `blur` event also if you actually looked the source.

I initially made this fork to add `disabledValues` only. The original repo doesn't even have any event other than `input` or `change`. I dont even know why there is `change` when `input` was enough.

Instead of saying it is useless, why not describe your problem properly? Or go fork and make your own?

Your issue looks useless to me.
